/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './app/**/*.{js,ts,vue}',
    './components/**/*.{js,ts,vue}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Vazirmatn', 'system-ui', 'sans-serif'],
      },
      colors: {
        primary: "#00236f",
        accent: "#FF6700",
        "background-light": "#f8f9fb",
        "background-dark": "#111421",
        "text-main": "#0e111b",
        "text-muted": "#505d95",
        neutral: {
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
        },
        truncate: '#505d95',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
        rating: {
          good: '#22c55e',
          average: '#eab308',
          bad: '#ef4444',
        },
        didars: {
          blue: '#1e3a8a', // Deep blue
          light: '#f3f4f6',
          accent: '#3b82f6',
        },
        "background-light": "#f8fafc",
        "background-dark": "#0f172a",
        "card-light": "#ffffff",
        "card-dark": "#1e293b",
        "text-light": "#1e293b",
        "text-dark": "#f1f5f9",
        "text-muted-light": "#64748b",
        "text-muted-dark": "#94a3b8",
        "border-light": "#e2e8f0",
        "border-dark": "#334155",
        "text-main-light": "#1f2937",
        "text-main-dark": "#f9fafb",
        "text-sub-light": "#6b7280",
        "text-sub-dark": "#9ca3af",
        "border-light": "#e5e7eb",
        "border-dark": "#374151",
        "surface-light": "#f3f4f6",
        "surface-dark": "#1e293b",
        "outline": "#757682",
        "outline-variant": "#c5c5d3",
        "surface-bright": "#f7f9fb",
        "on-surface": "#191c1e",
        "surface": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed": "#ffdbcb",
        "error-container": "#ffdad6",
        "surface-dim": "#d8dadc",
        "tertiary": "#4b1c00",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-bright": "#f7f9fb",
        "on-secondary-container": "#fefcff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#2170e4",
        "on-primary-fixed": "#00164e",
        "surface-container": "#eceef0",
        "tertiary-container": "#6e2c00",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary": "#ffffff",
        "inverse-primary": "#b6c4ff",
        "on-surface": "#191c1e",
        "inverse-surface": "#2d3133",
        "surface-tint": "#4059aa",
        "outline": "#757682",
        "on-primary-fixed-variant": "#264191",
        "surface": "#f7f9fb",
        "tertiary-fixed-dim": "#ffb691",
        "surface-variant": "#e0e3e5",
        "surface-container-highest": "#e0e3e5",
        "inverse-on-surface": "#eff1f3",
        "on-background": "#191c1e",
        "on-tertiary-container": "#f39461",
        "background": "#f7f9fb",
        "secondary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#adc6ff",
        "on-surface-variant": "#444651",
        "on-secondary-fixed": "#001a42",
        "primary-fixed": "#dce1ff",
        "on-tertiary-fixed-variant": "#773205",
        "on-primary-container": "#90a8ff",
        "surface-container-high": "#e6e8ea",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#004395",
        "secondary": "#0058be",
        "primary-container": "#1e3a8a",
        "star-rating": "#fbbf24",
        "surface-white": "#FFFFFF",
        "text-primary": "#212529",
        "badge-container": "#e6eff8"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "pill": "9999px"
      },
      boxShadow: {
        'card': '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        'card-hover': '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
        'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)'
      },
      spacing: {
        '4.5': '1.125rem',
        "base-unit": "4px",
        "section-gap": "24px",
        "margin-desktop": "24px",
        "margin-mobile": "16px",
        "max-width": "1400px",
        "gutter": "16px"
      },
      width: {
        '1/3': '33.333333%',
        '2/3': '66.666667%',
        '3/3': '100%',
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "44px", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-xl": ["40px", { "lineHeight": "56px", "fontWeight": "800" }]
      }
    },
  },
  safelist: [
    'w-1/3',
    'w-2/3',
    'w-3/3',
  ],
  plugins: [],
}